apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: mc
spec:
  version: {{ .TagName }}
  homepage: https://github.com/jonnylangefeld/kubectl-mc
  shortDescription: Run kubectl commands against multiple clusters at once
  description: |+2
    This plugin helps to work with multiple kubernetes clusters at once, filtered by
    a regular expression. For instance to get the status of a deployment across all
    `staging` clusters run the following command:
    kubectl mc -r staging -- get deployments -n kube-system
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/jonnylangefeld/kubectl-mc/releases/download/{{ .TagName }}/kubectl-mc_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-mc
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/jonnylangefeld/kubectl-mc/releases/download/{{ .TagName }}/kubectl-mc_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-mc
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/jonnylangefeld/kubectl-mc/releases/download/{{ .TagName }}/kubectl-mc_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-mc
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/jonnylangefeld/kubectl-mc/releases/download/{{ .TagName }}/kubectl-mc_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    bin: kubectl-mc
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/jonnylangefeld/kubectl-mc/releases/download/{{ .TagName }}/kubectl-mc_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-mc.exe
